feat: 增加arc动画往返&和动画次数功能
huiyan-fe/mapv pull request #249
Opened 2021-01-13 03:42 UTC by proto1994

因业务需求，需要在迁徙动画中增加往返和动画次数功能

```javascript
 this.animationLayer.update({
        options: {
          animateTime: 100,
          fillStyle: '#0087f6',
          size: 3,
          isRound: true, // 是否往返
          times: 2, // 动画次数
        },
 });
```
效果入下视频所示

https://user-images.githubusercontent.com/12874077/104403735-22a9b480-5594-11eb-8e17-04183d383ad7.mp4

2021-01-15 05:48 UTC, Junior2Ran requested changes
新增功能情况下，需要充分考虑向前兼容问题

2021-01-15 05:48 UTC, Junior2Ran commented on src/map/baidu-map/AnimationLayer.js
> +                        !hasCalcAnimateTimes && this.options.times--;
times属性未声明情况下，没有容错

2021-01-15 05:48 UTC, Junior2Ran commented on src/map/baidu-map/AnimationLayer.js
> +                        !hasCalcAnimateTimes && this.options.times--;
times属性未声明情况下，没有容错

2021-01-15 05:48 UTC, Junior2Ran commented on src/map/baidu-map/AnimationLayer.js
> +                        hasCalcAnimateTimes = true;
此处逻辑难以理解，建议梳理，或者添加注释

2021-01-18 11:11 UTC, proto1994 commented
多谢指出代码中的不足

优化了下代码，并且增加动画循环后停留时长
```javaScript
 this.animationLayer.update({
        options: {
          animateTime: 100,
          fillStyle: '#0087f6',
          size: 3,
          isRound: true, // 是否往返
          times: 2, // 动画次数
          stayTime: 2000, // 动画循环完一次后 停留两秒在继续
        },
 });

```

2021-01-18 11:21 UTC, merged